### PR TITLE
mDNS support

### PR DESCRIPTION
**Pull request by fabdrol**
I'd like to merge the `mdns` branch into master. @tkurki: I haven't added unit tests, which is not good, but I'm not entirely sure what I can test. Perhaps a config check (verifying that it loads when it should and doesn't when it shouldn't) is do-able, but that's not very meaningful. Ideas?

@zapfware, you have tested the branch with the app. Any changed you'd like to propose before we merge? The `_signalk-ws` service is broadcasted with service type `tcp`.. is that good or should it be `http` or even `ws`?

### CODE REVIEW

**Comment by fabdrol** [comment]
btw @tkurki regarding the `start()` functions: I agree, but we needed it here as well and it's such a small thing that I couldn't be bothered with doing a separate branch of master and then rebasing this one..

**Comment by tkurki** [comment]
Now that we have the capability to start & stop the server from tests starting it with the different configs (mdns on/off) and asserting that it advertises correctly would make a great functional test & an example test to build more tests on. 

Might be a bit tricky with timings to assert that it doesn't advertise.

Feel like doing this?

**Comment by tkurki** [comment]
Bonjour/mDNS service type is tcp or udp afaik, so in our case tcp, so the services we are advertising are `_signalk-http` and `_signalk-ws`, in the future  `_signalk-tcp`.


http should be removed here https://github.com/SignalK/signalk-server-node/blob/5277da725572d168221433f40cee7af969c8b3f4/lib/interfaces/mdns.js#L51

**Comment by tkurki** [comment]
- [ ] remove http reference
- [ ] update Readme to document mDNS and how to disable it

**Comment by tkurki** [comment]
Since Signal K server is also a regular http server we should also advertise simple `_http`.

**Comment by tkurki** [comment]
See #36

**Comment by tkurki** [comment]
I consider this done.

**Pull request merged**
