### PR TITLE
feature: new multiplexed provider that autodetects input type

### PR DESCRIPTION
**Pull request by sbender9**
I'm sure there's a better way to do this. Brain dead right now,

### CODE REVIEW

**Comment by sbender9** [comment]
I did the wrapper cause `multiplexedlog` did not make sense, but most of the needed code was already there. Want me to do it some other way?

I'm fine with universal as the name.

**Comment by tkurki** [comment]
How about doing this the other way around: rename multiplexedlog.js to universal.js and create a wrapper named multiplexedlog.js to retain backwards compatibility?

**Comment by tkurki** [comment]
On second thought universal is probably too universal - autodetect.js maybe?

**Comment by sbender9** [comment]
I think throttle should be in the piped providers. You would not want throttle when using this with live data, Not sure what you mean by "fast format timestamp should be parsed"

**Comment by tkurki** [comment]
I meant that if you are using this with input from a file there needs to be throttling somewhere. For deltas and nmea0183 it needs to throttle by data rate, for fast format it needs to parse the timestamp.

But If this is used only with live inputs then none of that matters and it is mergeable. What do you think?

**Pull request merged**
