### PR TITLE
feature: use timestamp from multiplexed log

### PR DESCRIPTION
**Pull request by tkurki**
Override N2K timestamp with the value from the multiplexed log.

Depends on [a change in canboat](https://github.com/canboat/canboatjs/pull/48).

### CODE REVIEW

**Comment by sbender9** [comment]
canboatjs has been released with the required change.

**Comment by tkurki** [comment]
Rebased & bumped canboat/canboatjs version.

**Comment by sbender9** [comment]
Is this still WIP?

**Comment by tkurki** [comment]
No.

**Pull request merged**
