### PR TITLE
[WIP] feature: store plugins outside of the server so that they retained

### PR DESCRIPTION
**Pull request by sbender9**
This addresses issue #304 

Plugins are installed to plugin-config-data/node_modules, so they are retained after removing ./node_modules.

When used in combination with the `-c` option, they are stored completely separately from the node server installation.

### CODE REVIEW

**Comment by sbender9** [comment]
Seems pretty smooth. The plugins don't even need to be re-installed. They will just be there, even with a brand new node-server install.

**Comment by sbender9** [comment]
Needs a re-working of the way paths, etc. are handled. So just a POF right now.

**Comment by tkurki** [comment]
I think this would be a valuable feature. What needs to be done?

**Comment by sbender9** [comment]
I'll get back on this. Will go well with the ability to install the server globally.

**Comment by sbender9** [comment]
This is now part of #381

**Pull request closed without merging**
