### PR TITLE
Feature: add Signal K JSON over serial support in admin UI

### PR DESCRIPTION
**Pull request by tkurki**
Add the ability to add providers that receive line oriented Signal K delta JSON over serial.

### CODE REVIEW

**Comment by tkurki** [comment]
I have not been able to test this, as I don't have a handy test setup.

**Comment by tkurki** [comment]
@joabakk do you a setup that you could use to test this?

**Comment by joabakk** [comment]
Not currently, but it’s not very complicated code?

**Comment by tkurki** [comment]
Not complicated, but nicer to verify that it works than merge blindly.

**Comment by joabakk** [comment]
I'm trying to build the admin-ui to test this out, but I get an error not related to this PR when I run `npm run prepublishOnly`:
```Hash: 5fdcbd945716db0d8edb                                                         
Version: webpack 3.12.0
Time: 2125ms
                           Asset       Size  Chunks             Chunk Names
                 index.bundle.js    7.97 kB       0  [emitted]  index
             index.bundle.js.map    69.4 kB       0  [emitted]  index
                      index.html  520 bytes          [emitted]  
             img/logo-symbol.png    7.18 kB          [emitted]  
                 img/favicon.ico    15.1 kB          [emitted]  
img/signal-k-logo-image-text.svg    10.8 kB          [emitted]  
[./src/index.js] ./src/index.js 260 bytes {0} [built] [failed] [1 error]
   [0] multi ./src/index.js 28 bytes {0} [built]

ERROR in ./src/index.js
Module parse failed: Unexpected token (45:8)
You may need an appropriate loader to handle this file type.
|     if (action.type === 'RECEIVE_PLUGIN_LIST') {
|       return {
|         ...state,
|         plugins: action.data
|       }
 @ multi ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    [./node_modules/html-webpack-plugin/lib/loader.js!./public_src/index.html] ./node_modules/html-webpack-plugin/lib/loader.js!./public_src/index.html 488 bytes {0} [built]```

**Comment by tkurki** [comment]
What version of Node?

WOMM with a fresh clone, Node v8.12.0 `npm install && npm run prepublishOnly`.

**Pull request merged**
