### PR TITLE
feature: allow third party apps to integrate with security

### PR DESCRIPTION
**Pull request by sbender9**
Specifically done to enable security for node

### CODE REVIEW

**Comment by sbender9** [comment]
Having issues. I can't git this to work with our security middleware...

**Comment by tkurki** [comment]
Ok. But then just cherry pick 3ee4060? I can take a look at this over the weekend.

**Comment by tkurki** [comment]
```
  1) Security
       websockets acls work:
     Uncaught TypeError: Cannot read property 'id' of undefined
      at update.values.update.values.map.valuePath (lib/tokensecurity.js:439:22)
      at Array.map (<anonymous>)
      at delta.updates.delta.updates.map.update (lib/tokensecurity.js:437:14)
      at Array.map (<anonymous>)
      at Object.strategy.filterReadDelta (lib/tokensecurity.js:435:10)
      at aclFilter (lib/interfaces/ws.js:117:45)
      at onChange (lib/interfaces/ws.js:223:15)
```

**Comment by sbender9** [comment]
Yeah, I guess maybe running the tests first would have been a good idea...

**Pull request merged**
