### PR TITLE
feature: add stdout sending to TCP Client connections

### LINKED ISSUE #1054: Missing output option in NMEA0183 TCP client
I'm trying to configure a TCP client (which connects to GPS/chartplotter) to send AIS messages to the client? (to phase out kplex from the setup)

When configuring a serial connection there is the possibility to  specify 'Output Events' and use the  nmea0183-to-nmea0183 plugin, but this appears not be available for tcp client.

Hence the TCP client seems only possible to allow input and can't be used for output

### PR DESCRIPTION
**Pull request by marcelrv**
Add sending to defined stdout events to TCP connection.
As similar option is available in the serial connection

Fixes #1054

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by tkurki** [comment]
@sbender9 you added `outEvent` in d163d02aa0f5ca721075e55b196d8fc5a698aaba, but I don't think many people are using it, as it is missing from the ui. Should we add it to the ui, maybe as _raw output event_ or something?

**Comment by sbender9** [comment]
It is used by ydgw and NavLink2 connections, but that is setup under the hood. 

I do think we should add it to the ui for 0183 tcp connections.

**Comment by tkurki** [comment]
I think it would just cause confusion in nmea0183 context - an extra event field that is practically never used.

**Comment by marcelrv** [comment]
@tkurki  yes, that was already added... probably right at the time of your review.

There is still something weird that I don't grasp. It was working, but not it does not anymore.
It errors out 
```
TypeError: this is not a function
    at TcpStream.pipe (C:\Users\Marcel\Documents\programming\node\signalk\signalk-server-node\packages\streams\tcp.js:59:5)
    at new Simple (C:\Users\Marcel\Documents\programming\node\signalk\signalk-server-node\packages\streams\simple.js:72:17)
    at createPipeElement (C:\Users\Marcel\Documents\programming\node\signalk\signalk-server-node\lib\pipedproviders.js:56:20)  
```

**Comment by tkurki** [comment]
Thanks, I fixed it in db1c2daa2ca2738b18581fe528294dbce1e9af46.

**Pull request merged**
