### PR TITLE
feature: implement device access and new security spec

### PR DESCRIPTION
**Pull request by sbender9**
TODO: 
- [x] Do a write up with screenshots
- [x] UI to edit devices
- [x] Create tests
- [x] Add WS implementation 
- [x] Update plugin documentation on put requests
- [x] Add tests for device access requests
- [x] Add tests for put requests
- [x] prune old requests

This PR provides a way for devices to request an access token from the server.  

It also has changes to conform to the new request/response and security specifications.

The device will send a REST request to the server:

`curl -k --header "Content-Type: application/json"  --request POST --data '{"clientId":"1234-45653-343453","description": "My Awesome Sensor"}'  https://localhost:3443/access/requests`

The server will return a json response with a request identifier:

`{"requestId":"60240a45-bbcb-46f0-8df6-c7a3e048bec0"}`

A Signal K notification is sent out when this happens and In the admin ui, there is a list of devices that are requesting access:

image

In the mean time, a device should poll the server using the requestId in the response above to see if it has been granted access and get the token:

The request is pending:
```
$ curl -k https://localhost:3443/access/requests/ee759b2b-9051-4188-ab2d-56b97f2a58eb
{"status":"PENDING"}$ 
```

The request is denied:

```
$ curl -k https://localhost:3443/access/requests/ee759b2b-9051-4188-ab2d-56b97f2a58eb
{"status":"'DENIED'"}$ 
```

The request was approved:

```
$ curl -k https://localhost:3443/access/requests/ee759b2b-9051-4188-ab2d-56b97f2a58eb
{"status":"APPROVED","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2UiOiIxMjM0LTQ1NjUzLTM0MzQ1MyIsImlhdCI6MTUzNjg4NDY5MSwiZXhwIjoxNTY4NDQyMjkxfQ.5wypdKin5Q-gsi9aQ8sN1XBAP8bt3tNBT1WiIttm3qM"}
```

On approval, the device would save the token in a secure way and use it when sending or requesting data. Subsequently, when a device gets an 'Access Denied' response, it should send a new request for access to get a new token.

In the same vane, this PR also provides a way for users to request access to the server.

The login page now shows a "Sign Up" link:

image

The user will then be presented with a page to enter an email address and password:

image

A notification is sent out when this happens and In the admin ui, there is a list of users that are requesting access:

image

Example of a client that could allow users to easily approve requests:

image

### CODE REVIEW

**Comment by inspirity** [comment]
Great idea! How would you handle the metadata info for the requesting device? 
Is there a way for the new device to populate basic info or should this be done manually?

**Comment by sbender9** [comment]
Not sure exactly what your asking, but I have an open PR in the spec for meta data : https://github.com/SignalK/specification/pull/454

And a PR on node server: https://github.com/SignalK/signalk-server-node/pull/481

Is this the "metadata info" you are referring to?

**Comment by inspirity** [comment]
yes exactly, with the meta delta a new device could populate some of the meta after approval.

**Comment by tkurki** [comment]
What if the initial connection request had a way to include more info about the requester? Now there is just one string, how about including something like meta deltas?

**Comment by inspirity** [comment]
Yes this would help. We should be aware that some devices can have limitations to handle long Strings. 
Specially some simple sensors. So there should still be a wat to set the meta data in a separate message.

**Comment by tkurki** [comment]
Yep, meta deltas will be available for all devices.

**Comment by zubenubi** [comment]
What kind of sensors/devices are you imagining? All IP connected?

**Comment by sbender9** [comment]
Not sure I understand what the user case is here for meta data. Can you give me an example of what a device would supply?

**Comment by sbender9** [comment]
@zubenubi yes, this is for IP connected devices.

Really could be any kind of device, like a display, engine sensors, wind sensors, etc.

Clients could even use this. So for example, when your buddy gets on your boat, he can open WilhelmSK, it makes an access request, you get a notification on your phone and go give him read-only permission. No need to create a userid/password and then have to type it in the app.

**Comment by ba58smith** [comment]
@sbender9 Is this intended to replace the current CLI approach of getting a Security Token with signalk-generate-token? Want to make sure I understand the purpose.

**Comment by sbender9** [comment]
Yes, this removes the need to manually create the token and configure it on the device. The script won't go away, so it can still be done the old way.

**Comment by ba58smith** [comment]
> Yes, this removes the need to manually create the token and configure it on the device. The script won't go away, so it can still be done the old way.

Excellent! That's what I was hoping. Thanks.

**Comment by fabdrol** [comment]
Looks good, I like this kind of approach. Some thoughts:

- Should requests expire?
- Should a requesting device have the option to expire a pending request? 
- From the screenshots (haven't had time to read through the code yet) it seems that a request is fairly simple. What can a device ask for? I.e. to me it doesn't make sense that a device that asks for READ ONLY access is given WRITE access, even if the user grants it. Giving the user the option to set the kind of access (READ ONLY, WRITE or ADMIN) makes sense when granting access to another user, but doesn't make sense when it's a device (e.g. sensor) with specific capabilities IMHO

**Comment by sbender9** [comment]
@fabdrol 

* Yes, requests should expire. I have not done that yet.
* I'm not sure I see the real world use case where the device would need to expire a pending request?
* Hmm. Good point. Currently the just asks for access and the admin decides what to give it. But I think I'll change to give the device the option of requesting specific permissions, in that case the admin would not be able to change it.

**Comment by fabdrol** [comment]
@sbender9 you'r right, I can't think of one. I guess I was thinking of proper "cleanup", on shutdown or retry, but why bother? It could just do a new request after startup and let server bother with the invalidation of the "old" request. If that expiry is implemented, it's never a problem.

How does the notification -> reply work? I.e. the notification is just a delta message (I assume), which disappears from the tree after the request has been granted, denied or has expired? The reply is just a HTTP request from a client?

**Comment by sbender9** [comment]
@fabdrol The client gets a uuid in the response when make the access request. It then polls using that uuid to get the response.

**Comment by rob42** [comment]
I agree we need this functionality but all data needs to be in a signalk message, rather than depending on the url for context, eg 

`{ "accessRequest": {"uuid":"1234-45653-343453","description": "My Awesome Sensor"}}`

The reason is simple, how do I make an access request (using a url) if I have a device on some other form of connection (serial, MQTT, STOMP, COAP)? 

We need to ensure everything in signalk can be done without depending/assuming http/url/webbrowser

**Comment by sbender9** [comment]
@rob42 I agree that we need to support other transports, but I think for a REST interface, it should like normal REST calls. You would not have "accessRequest", in the REST interface. Would you agree?

I think I'll go ahead and do a WS implementation of this. In that case I would do as you said, and then could be used for other transports as well.

**Comment by rob42** [comment]
Agreed, the REST interface already 'knows' the context of the data.

This is also consistent with the other REST interfaces, when we GET .../navigation/position it just returns the lat/lon object, not the full tree. 

 In the artemis-server case the REST interface is a facade for the signalk message, it would just construct the full message and send into the signalk server anyway, and await and return the response.

**Comment by rob42** [comment]
It would be good to align the message format with the current norm for updates/GET/PUT/LIST messages
See https://github.com/SignalK/specification/wiki/Get,-Put-and-List-messages

I think we should have more tags at the `context` level, eg `login`, `password`, `token` etc, to allow security, and add `access` (? needs a better name), so

```
{ 
    "context": "vessels.self",
    "token": "gsgggsggsggsgsggsgsggsgsggsgsgsggsggsgsg",
    "access": {
          request": {"uuid":"1234-45653-343453","description": "My Awesome Sensor"}
          "status": ....
          ....
       }
}
```

**Comment by rob42** [comment]
I had a look but Im not familiar with the code or the libs used so I cant make much of it Im afraid.  Sorry I dont have the time to study up on them at the moment. We really need to make a schema change to allow a set of new keys to the delta format to allow this and other tasks but I'm buried next few days

**Comment by sbender9** [comment]
I just want you to look the at the ws messages. I can do a PR to the spec once this is ironed out.

**Comment by rob42** [comment]
sorry for being dense, I cant see any ws samples?

**Comment by sbender9** [comment]
It's in the PR description above, search for "Requests can also be made via web sock or other protocols"

**Comment by tkurki** [comment]
What is the role of `context` in the ws request? What values could it have in request/response? What should/could the client do with the context value?

_Device access not allowed_ is not a good example of an ERROR, as that should result in DENIED.

The messages are not symmetric, request is `access.request` but response is just `access`. What do you guys think of just `accessRequest` and `accessResponse`?

If the client drops the ws connection before receiving confirmation how does it get the response if the request was granted/denied while it was not connected? What if the client never sees 

I updated the messages in the description to include the uuid for request-response collation. This makes the uuid a _client issued request id_ instead of a _client id_, which was probably what Scott suggested originally. Is this the way it should be? In REST things are different, as the server issues the request id. I think it would be better to not use the name `uuid` but something semantic like `clientId` and `requestId`, the value being uuid is sort of an implementation detail.

I think it would make sense to start working on this as a PR to specification in parallel with the implementation, if for nothing else than gaining Github versioning and diffing for the spec addition. Appendix or a new chapter? Lest the specification never happens...

BTW I would be happy with just getting this defined for REST, ws adds quite a bit of complication in spec and implementation.

**Comment by sbender9** [comment]
I agree with leaving ws out of this for now. We need to define how request/response is done and this is not the place to do it. I was thinking that this is a special case since you can only make one access request per connection, so you don't need to correlate.

My thinking for losing a connection or missing a response is that the device would have to make another request. But again, this is probably something that needs to be considered on an over request/response spec.

I will change uuid to clientId. This was meant to be a unique id for the client. And yes, should be anything, could be a model and serial #, etc.

I will also start on a PR to specification.

**Comment by sbender9** [comment]
specification PR: https://github.com/SignalK/specification/pull/505

**Comment by rob42** [comment]
the ws case is the same as the async case for protocols like serial,MQTT, COAP, TCP etc. I dont think it can be left out, and its not especially complex. 

In the artemis/java server the web API is just a facade over the async message anyway, it just creates a signalk message and passes it on into the main server, so I need to implement a full async protocol to make this work.

Re above:

`context` is there because its always there!. Not sure if its `required` in the format. It has no relevance to this case, but does no harm.

`access` - having all the access keys under a sub-object just makes the routing code cleaner, eg a plugin/filter/interceptor is only looking or ignoring `access`, rather than `accessRequest`, accessResponse` etc. Also easier to remove from messages for security reasons so we dont leak data.

`clientId` - yes, the clients unique identifier, supplied by client

`requestId` - not needed for REST as its inherent in the connection. For async it should be generated by the client. In my server the REST api generates a `requestId` and adds it to the async message. When the async reply returns its used to map back to the correct REST call.

dropping response - a request/response should have a valid lifetime/timeout, even if its a default 1 hr. It should be idempotent, so repeating a request is valid, it just creates a second (valid) token, the first expires in due course.

**Comment by tkurki** [comment]
>It has no relevance to this case, but does no harm.

Unused, irrelevant fields are a source of confusion and thus do cause harm. There is no _it’s always there_ practise afaik.

**Comment by tkurki** [comment]
Note that REST results in async behavior here: the first http call creates the grant request and returns the request id, that the client will later use to check the status of the request. RequestId is not _inherent in the request_ but an important part of the message exchange.

**Comment by tkurki** [comment]
I don't see how this is a _delta_. What would be the advantage to think it is? The message content and semantics are totally different.

Also referring to the current delta schema doesn't really make sense: for example `access` is not there either. We are doing something new, the existing schema need not cover it.

**Comment by rob42** [comment]
The current delta format needs extension to include at least `token` in the header. We are all familiar with the format, and have code to create/process it, so it seems simplest to add an `access` object, and use the format for more than just deltas.

We could add an `authenticate` object and handle the login/passwd stuff too.

**Comment by rob42** [comment]
When giving permissions to a device the optimal way to do it is to provide RW based on keys, and using wildcards, just as we do via subscribe etc. So a device will request READ for a list of keys, and WRITE for another list. Bit like android permissions, you can grant/deny each.

Probably there would be defined 'profiles' to save a lot of detail, eg `profile.anemometer` etc.

I think we should do the definition of that later (a lot of work), after the basics are settled, but the design should be compatible with that concept.

**Pull request merged**
