### PR TITLE
Fix: Allow running a SignalK Server with a simple include

### PR DESCRIPTION
**Pull request by taggie05**
#548 Changed the _dirname path to app.config.configPath so that users would be able to set their own configurations. We are now able to use a .env file to set up our own configurations and just npm install signalk and use it as a dependency. This allows for a more robust and flexible use of signalk.

### CODE REVIEW

**Comment by sbender9** [comment]
The code above your change does the exact same thing. See line #31.

This change would make so that we don't load plugins that get installed by default.

Will look more into it tomorrow, but `app.config.appPath` might be the right choice here.

**Comment by taggie05** [comment]
Thank you for pointing that out @sbender9. We realized that we just needed a check for that folder. We reconstructed the function with keyword to create the check and so that it would be able to check the app.config.configPath without throwing an error message. Before we did this change we would get a package.json not found. With this fix no errors were thrown.

**Comment by taggie05** [comment]
@tkurki when we tried changing the configuration path to our own folder in our application and using SignalK as a node module we would get an error stating that our configuration path was not in the specified location, even though it was, we reconstructed the function so that this would not happen. So now on our application can use SignalK as a node module. Since we were only using certain functionality from SignalK before this fix we had to manually change the bit of code so that we wouldn't get this error.

**Comment by webmasterkai** [comment]
I believe @sbender9 is correct. `app.config.appPath` is what we're looking for here. I'm setting `appPath` with the value returned from the [app-root-path](https://www.npmjs.com/package/app-root-path) module and making the change in the first commit with `appPath` fixes this for me.

I'll submit a pull request on the pull request.

**Comment by webmasterkai** [comment]
Okay @taggie05 I made a pull request https://github.com/taggie05/signalk-server-node/pull/1 If you merge that I believe it will update the code here. I also merged the master branch.

**Comment by tkurki** [comment]
Did #601 take care of everything here?

**Comment by webmasterkai** [comment]
I have to check a couple things that I was working on with #595 to see if anything is left. I'm working on this today.

**Comment by tkurki** [comment]
I am closing this, things proceed in #695, #689, #691. Let me know if we missed something.

**Pull request closed without merging**
