### PR TITLE
[WIP] feature: add registerDeltaInputHandler plugin hook

### PR DESCRIPTION
**Pull request by tkurki**
Add addDeltaInputHandler so that plugins can intercept
incoming delta messages and alter them before the server
handles them.

### CODE REVIEW

**Comment by sbender9** [comment]
Going to get a little hairy if more than one plugin does this, right?

**Comment by sbender9** [comment]
After playing with this with node red. I think we should maintain a 'chain' of these, this way they can be inserted and removed adhock. Maybe the register function should take a 'priority' parameter, which could be configured by the user. This would allow plugins to stop/restart and the chain could be kept consistent. Still thinking about how this would work and fit into node-red.

https://github.com/SignalK/node-red-embedded/tree/delta-input-handler

**Comment by tkurki** [comment]
Note force push! 

Rewritten as a chain of handlers that are added and removed upon plugin start/stop.

TODO:
- [ ] plugin API documentation
- [ ] generate the `next` functions on chain modification, no need to create new functions on the fly for each and every handled delta, probably really hurts performance.
- [ ] ordering/priority?

Priority should be easy enough to implement, just insert the handler in the correct position and not just push to the end of the chain. That should go into plugin config, as a sibling of `enabled`? Should the chain be debuggable someplace, show plugin ids in the chain in order? In the plugin config UI somewhere?

**Comment by tkurki** [comment]
Added some documentation and streamlined dispatching so that we don't create new functions per each delta and chain element.

I think we can address the priority issue when we bump against it.

**Pull request merged**
