### PR TITLE
Upgrade to use officially Node 6

### PR DESCRIPTION
**Pull request by tkurki**
I've been running the server for quite a while on Node 6.

Unless there are compelling reasons we should upgrade to the latest major version, which now is 6.

### CODE REVIEW

**Comment by joux3** [comment]
Perhaps also add a `.nvmrc`[0] file stating the Node.js version?

[0] https://github.com/creationix/nvm#nvmrc

**Comment by tkurki** [comment]
Done.

**Comment by joabakk** [comment]
Related to #73 ? You wanted some help?

**Comment by tkurki** [comment]
#73 outlines the tasks. The main thing to do is to upgrade all SK components CI on travis to use Node 6 and make sure they pass on your own fork, then PR the changes.

Then there is the RPi installation instructions in this repo.

**Comment by sailoog** [comment]
OpenPlotter will keep nodejs 4 LTS because is the only version supported by node-red, node-red-dashboard and node-red-freeboard. I guess it will be backward compatible, I will report if any problem is detected.

**Comment by tkurki** [comment]
@sailoog https://github.com/node-red/node-red/blob/master/.travis.yml#L16

http://nodered.org/docs/hardware/raspberrypi#upgrading
>As of version 0.14.x there is a script in the pre-installed version of Node-RED that will do a full upgrade to the latest nodejs LTS and latest release version of Node-RED.

**Comment by sailoog** [comment]
AFAIK latest nodejs LTS is 4.

Tested node-red-dashboard and node-red-contrib-freeboard with nodejs 6 and multiple crashs.

**Comment by tkurki** [comment]
It is 6 since last week: https://github.com/nodejs/LTS

**Comment by sailoog** [comment]
ops you are right.
I will try to find out the node-red-dashboard and node-red-contrib-freeboard plans.
Do you think signalk-server-node could be in trouble with nodejs 4? I was using 6 but I went back to 4 when I implemented these dashboards due to crashes.

**Comment by tkurki** [comment]
This is for keeping up with things/not falling behind and development comfort that new ES features bring.

**Comment by tkurki** [comment]
@sailoog any updates?

BTW I recommend that Open Plotter should consider nvm https://github.com/creationix/nvm. It allows peaceful coexistence of different Node versions.

**Comment by tkurki** [comment]
I am about to merge `plugins` where the changes in this branch are already merged.

**Comment by sailoog** [comment]
ok.

**Comment by tkurki** [comment]
Merged manually.

**Pull request closed without merging**
