### PR TITLE
chore: create @signalk/plugin-config package within same git project

### PR DESCRIPTION
**Pull request by webmasterkai**
Move `plugin-config` to `/packages/plugin-config`. This makes it easier for this github repo to be used as a "monorepo" and for `plugin-config` to be its own `npm` module.

Since `plugin-config` is its own module it should have its own ignore files. This removes old rules from the root and adds them to `packages/plugin-config` directory.

### CODE REVIEW

**Comment by webmasterkai** [comment]
This is ready to review. Server changed the way we get the public path of for plugin-config assets. Using new [get-installed-path](/tunnckoCore/get-installed-path) dependency makes it easy. Server now works with `plugin-config` as a package. In prep for the future I created `/lib/config/get/getPluginConfigPublic()` that returns needed path.

**Comment by sbender9** [comment]
I don't think we need this get code. You can just use app.config.appPath

**Comment by webmasterkai** [comment]
Where would we use `app.config.appPath`?

**Comment by sbender9** [comment]
On second thought. Lets keep it.

**Comment by sbender9** [comment]
Can you come up with a better title. Something will make more sense to a layman in the CHANGELOG

**Pull request merged**
