### PR TITLE
feature: Add npm based webapps in favor of bower

### PR DESCRIPTION
**Pull request by tkurki**
Add npm based webapps, which can be installed with npm install and show up
under /apps, just like bower installed webapps have shown. SK webapp modules
are marked with signalk-webapp keyword in package.json. Bower and npm based
webapps can coexist. This change supports also npm modules that provide
both a webapp interface (their entire contents are available under the
server's html root) and a plugin interface.

### CODE REVIEW

**Comment by tkurki** [comment]
- [ ] update documentation
- [ ] update standard webapps to use npm installation (get rid of bower)

**Comment by tkurki** [comment]
I believe this is ready for merging.

**Comment by ph1l** [comment]
Testing this branch, I have duplicate entries for Instrumentpanel and sailgauge the bottom of my list on `/apps/`. The duplicates link to the same URL, either `/instrumentpanel`, or `/sailgauge`...

**Comment by tkurki** [comment]
Bower based webapps are still supported, so one would need to clear bower_components. 

Maybe that support should be removed. Need to include Bootstrap anyway though. Hmmm.

**Comment by ph1l** [comment]
I'm okay with running a cleanup command to remove the old bower installed apps. Just wanted to point out that there seems to be ambiguous behavior. does the npm installed browser app install to the same directory? if not, which installation is /appName pointing to now?

**Comment by tkurki** [comment]
bower_components has precedence, npm modules are under node_modules.

You may be willing to clean up, but somebody else may not.

The easy option is to include Bootstrap files within the server git repo, not install anything with bower and not serve bower_components at all.

**Comment by joabakk** [comment]
I would go for the easy option, and merge the PR. If someone later updates their node server and get duplicates, it is only a matter of removing the bower_components folder?

**Pull request merged**
