### PR TITLE
Ignore ssl file permissions if on win32

### PR DESCRIPTION
**Pull request by zubenubi**
When node is running on windows the file permissions check on openssl .pem files are ignored

### CODE REVIEW

**Comment by sbender9** [comment]
You checked a bunch of files that you should not have. (7 files changed)

**Comment by zubenubi** [comment]
Uhoh.

How can I remedy?

charlie@im-design.net




On Wed, Aug 16, 2017 at 6:01 PM -0400, "Scott Bender" <notifications@github.com<mailto:notifications@github.com>> wrote:


You checked a bunch of files that you should not have. (7 files changed)

**Comment by zubenubi** [comment]
So - apologies for adding more files than I should have. Since doing so I have updated my .gitignore to exclude VS files and attempted a 'hard reset' and a sync. I was expecting that the pull request would be completely deleted but it seems to still be here. Please Advise

**Comment by tkurki** [comment]
You can adjust the branch locally to your liking and then force push to your github branch. The PR will reflect the state of your branch.

**Comment by zubenubi** [comment]
starting over

**Pull request closed without merging**
