### PR TITLE
feature: include details under sources for all devices on the network

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by tkurki** [comment]
Relates to https://github.com/SignalK/n2k-signalk/pull/154

**Comment by tkurki** [comment]
I'd like to try this out for real, will take a few days.

I'd like to include this data in the multiplexed data log - what do you think?

**Comment by sbender9** [comment]
Since the PGNs are logged, this does get into the the multiplexed logs.

**Comment by tkurki** [comment]
🤦‍♂

**Pull request merged**
