### PR TITLE
feature: add authentication and authorization support (WIP)

### PR DESCRIPTION
**Pull request by sbender9**
Allows authentication to be enforced for http, rest and streaming.

### CODE REVIEW

**Comment by sbender9** [comment]
@tkurki I cannot figure how to make /plugins* support both the web/html login and jwt . Any expericen there?

**Comment by joabakk** [comment]
Great work again. By the looks of it, I think we need to have an admin interface where security level and passwords can be set. If I understand correctly, will plugins break if they have not added authentication?
Since the vessels setting json file is often shared, would it make more sense to have the authentication info in defaults.json or a separate place such as plugins-config-data/ in the case of an administration plugin?
Perhaps the app store can be used to set permissions for each plugin and webapp?

**Comment by sbender9** [comment]
Plugins would not have to do anything. They would be automatically protected.

**Comment by sbender9** [comment]
Long term, users/permissions would definitely not be stored in the settings file. I could see different plugins supporting different kinds of authentication. And definitely a single plugin for user management.

**Comment by sbender9** [comment]
These are server details. Short term, this gives us a way to protect our boats. And is a good and simple start for getting security built into the spec. I think?

**Comment by joabakk** [comment]
Good, then we are in line

**Comment by sbender9** [comment]
Working on a different solution..

**Pull request closed without merging**
