### PR TITLE
[WIP] Move static vessel data to  defaults.json

### PR DESCRIPTION
**Pull request by tkurki**
Move the vessel identity and info to defaults.json from settings file. Replaces #182.

### CODE REVIEW

**Comment by tkurki** [comment]
Is this a breaking change so that existing settings files will no longer work @sbender9 ?

If it is I think it would be a good idea to add some code that tells the user what has changed and how to fix it. We can add some log statements about missing identity and possibly even allow the server to start but go into an error state where any http requests will return an informative message.

Does this affect rpi-setup.sh @joabakk ?

**Comment by sailoog** [comment]
Is there a way of calling defaults.json when it is out of settings folder?

**Comment by tkurki** [comment]
@sailoog what do you mean by _calling_? If you use some data from here it would be much better to use the sk server’s http api to get the data.

**Comment by sailoog** [comment]
We start the server running: 
`~/.config/signalk-server-node/bin/signalk-server -s ../../.openplotter/openplotter-settings.json`
Because we want the settings file out of the installation folder.
defaults.json is supposed to be always in ~/.config/signalk-server-node/bin/signalk-server/settings/
Could we place this file out of settings folder?

**Comment by sbender9** [comment]
You can use the new `-c` argument. It takes a path to a directory and will look for settings.json and defaults.json in that directory. (also puts plugin settings there)

**Comment by sbender9** [comment]
@tkurki @joabakk this code is so old, I think it definitely needs re-visited

**Comment by sailoog** [comment]
> You can use the new -c argument. It takes a path to a directory and will look for settings.json and defaults.json in that directory. (also puts plugin settings there)

@sbender9 Thanks!!! I was about to request something similar.

**Comment by joabakk** [comment]
I can PR the rpi-setup to this branch prior to merging

**Comment by joabakk** [comment]
I would like to see this merged, I think configurations will be more intuitive this way

**Comment by tkurki** [comment]
Now that settings has an API this needs more work.  Continue or abandon?

**Comment by sbender9** [comment]
closed for new #381

**Pull request closed without merging**
