### PR TITLE
feature: add script to report which serial devices the server is using

### PR DESCRIPTION
**Pull request by sbender9**
This is needed for the venus install, so that they can ignore devices that signalk is using

### CODE REVIEW

**Comment by mpvader** [comment]
Thank you!

Is the usage of ttys dynamic? Ie. can the list change while SignalK is runnning? Or does it need a restart?

On Venus side, what needs doing is calling `/opt/victronenergy/serial-starter/stop-ttys.sh [list of ttys separated with a space]`. It will tell the auto-starter aka serial-starter to stop whatever driver is using that tty and leave it alone, until next reboot.

If usage of ttys is static, we could simply run this once; from same bash script that starts SignalK server.

If not static, the we’d either need to call it in change; from within SignalK, or by monitoring its config file. Or periodically.

Note that stop-ttys.sh doesn’t need the full list every time.

For format: space separated would be best, better than to have to interpret JSON in bash.

**Comment by sbender9** [comment]
It's currently static. A restart is required when changed.

I changed tp [WIP] and will add an option for space separated output...

**Comment by mpvader** [comment]
Ok cool; FYI another place where they stop ttys script is used is here:
https://github.com/victronenergy/mqtt-rpc/blob/master/serialstopper.py

And then the call would go in here:
https://github.com/victronenergy/meta-victronenergy/blob/matthijs/signalk/meta-third-party/recipes-signalk/signalk-server/signalk-server/start-signalk.sh

**Comment by mpvader** [comment]
Perhaps though start-SignalK.sh is the wrong place: what happens if a user hits the restart button in SignalK-admin? Does it quit? To then be restarted by systemd (or in our case daemontools)?

Or is it in itself restarting?

**Comment by tkurki** [comment]
Just quits, restart by systemd / daemontools.

**Comment by mpvader** [comment]
Ok good, then that start script is a good place for stopping ttys in Venus.

**Comment by tkurki** [comment]
This approach is a bit brittle, as it is pretty far removed from the code path where serial ports are handled. As it stands it does not handle manually configured serial ports, which probably is not a problem.

Would it make sense to add a pre-hook to serialprovider? A script to call synchronously before opening the serial port?

And how to provide that - an env variable PRESERIALHOOK?

**Comment by mpvader** [comment]
What’s a manual configured port in SignalK?

Aren’t they all?

**Comment by tkurki** [comment]
Would something like #666 work here? 

That is part of the serial provider, so much more likely to stay onboard in the future, unlike something that is outside the server proper and relies on config file format.

**Comment by tkurki** [comment]
Superceded by #666.

**Pull request closed without merging**
