### PR TITLE
Debian package

### PR DESCRIPTION
**Pull request by mxtommy**
This pull request sets some build stages in Travis that use the npm package node-deb to build a Debian package, which is then pushed to packagecloud.io. 

There are 2 build stages.

1) The first builds all branches, with a packagename of "signalk-server-$BRANCH"(including master). So on every commit to every branch you get a package to test with. 

2) The second stage builds the main "signalk-server" package. This happens only on master branch, and only when the commit is tagged with a tag starting in "v[0-9]". 

There are 2 deploy stages on each build stage. This is only because of the different distributions (debian/raspbian). 

Note, that due to a few dependencies (bcrypt and mdns I think) build-essential is a dependency, and during the package install "npm install" is run to build them. If the package is popular enough it's possible that we could look into pre-compiling them, would need to see how to cross compile for arm though.

Regarding packagecloud, I have an account with the name "SignalK" that I got the opensource plan on. I can add collaborators, or I can look to transfer it over to someone else.

### CODE REVIEW

**Comment by tkurki** [comment]
Sorry for letting this lapse, getting back now.

Again, sorry for the conflicts from the docker stuff now in master's .travis.yml. There is now a stage for building x86 and arm docker images in parallel. In theory deb build could run in parallel with them, but not sure if it is a good idea. What do you think?

About the stages: the stages are now copies, except for the version, right? I'd like to avoid duplication, use the same "body" and just create the version conditionally.

I think releases should be based on git tags, not master commits. I think this rhymes well with creating the version conditionally, TRAVIS_TAG looks like it could do the trick.

jq looks superfluous?

I have stumbled a few times when trying to extract data from xml and json with command line hacks. Since the build environment is node I think it would make sense to parse the package.json with a short js script, like `echo "const data = require('./package.json'); console.log(data.version)" | node`.

How do we specify that this needs node >8?

**Comment by mxtommy** [comment]
The stages should be able to run concurrently. 

Only difference between the two stages build-deb-branch and build-deb-main are the debian package name. build-deb-branch names it "signalk-server-${TRAVIS_BRANCH}" while build-deb-main names its just "signalk-server". 

They could possible combined into one stage. I can look into it. 

Regarding releases, currently stage build-deb-main only runs when a tag is present. so the only packages  named "signalk-server" will be the tagged ones. Having the branch related ones permits two things, 1) making sure any changes don't break package building, 2) allows people to easily run pre-release versions (like latest master or a branch) Imagine someone requests support for some new thing, rather then wait for a new "release" they can just apt-get the branch and use it right away. :)

jq is a dependency for node-deb. (a system package, not npm dependency).

Fair point with the scraping json from command-line, your command looks much more "stable" :)

For specifying node8, I'll have a look. I think we can say we depend on "nodejs (>= 8.0)". I'll give it a try :)

**Comment by tkurki** [comment]
@mxtommy did we lose the momentum here? Winter's coming, lots of non-sailing time for tinkering with these....

**Comment by tkurki** [comment]
Don't really know.

AFAIK the npm method for installing and updating has served us well during the summer happening.

The server update does simply npm install for the latest version: https://github.com/SignalK/signalk-server-node/blob/84b007a300b13c651b3be331b0fa92038e153b95/lib/modules.js#L107-L109, but it has been out for just a few weeks and can't really tell how it will do.

On a related note I have been talking with @sbender9 about the setup script creating a separate signalk account and running the server under that, with limited priviledges.

Then there's also OpenPlotter. I just talked to @e-sailing last week about automating the OpenPlotter build as a solution for creating an always up to date RPi sd card image. There lies a practical problem: charts purchased from https://o-charts.org/ can not be (easily?) moved to a new installation, so upgrading via _get a new card_  is not attractive, even if we discount all your personal settings not being transferable. But it would still be a good starting point for getting into OpenPlotter/SK.

**Comment by lskillen** [comment]
@mxtommy  @tkurki Please feel free to consider [Cloudsmith](https://cloudsmith.io) as well for packaging. :-)

It's commercial but has very generous free plans and offerings for open-source projects (with 100GB of storage and 1TB of bandwidth by default). It might work well to consider splitting unstable releases into a separate repository (with support for npm as well if you need it), which will provide stable/unstable channels for your users. For actually building the packages I'd highly recommend [fpm](https://github.com/jordansissel/fpm) (worth a look whether you use Cloudsmith or not).

*Full disclosure*: I work for Cloudsmith, so might be biased (but only _slightly_, honest)!

**Comment by tkurki** [comment]
Npm global install method seems to have succeded to an extent that this is no longer such a need.

Thanks for playing!

**Pull request closed without merging**
