### PR TITLE
feature: support $PCDIN NMEA 0183 sentences

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by tkurki** [comment]
https://github.com/SignalK/signalk-server-node/blob/063a9d80f64fa56ead05909c26309f3f20471ccc/packages/streams/autodetect.js#L168 not enough?

**Comment by sbender9** [comment]
That's just for log file reading, no?

**Comment by tkurki** [comment]
Yes, but let’s have just one way to handle this instead of two.

Also don’t like renaming when requiring with FromPgn. I think it is one needless level of obfuscation.

**Comment by sbender9** [comment]
What do you propose to handle this one way?

**Comment by tkurki** [comment]
Let the new impl handle also log playback by removing the PCDIN clause in autodetect.handleMixed?

**Pull request merged**
