### PR TITLE
feat: Open npm url in new tab. Add link title.

### PR DESCRIPTION
**Pull request by webmasterkai**
As per mvader

### CODE REVIEW

**Comment by tkurki** [comment]
Maybe squash the doc related commits?

Was there something specific that prompted the sass update?

**Comment by webmasterkai** [comment]
Yeah, it was failing to compile on my machine. The version bump was mostly due to requiring node 5 or later. I thought all the commits got squashed on merge. Is it better that I do it now? Is it to make it easier to review?

**Comment by webmasterkai** [comment]
The compile process wasn't working on my machine. Said it wasn't yet compatible with my architecture. I tried updating sass-loader to the latest but the 6x-7x has breaking changes:

* Drop official node 4 support
* This slightly changes the resolving algorithm. Should not break in normal usage.
* Throws an error at runtime now and refuses to compile if the peer dependency is wrong.

**Comment by tkurki** [comment]
Doc added in #599. Npm links opening in #600 and published as @signalk/server-admin-ui@1.2.1.

Don't want to move ahead with Sass upgrade, it works on my machine after node_modules wipe and is a sidetrack to this PR, so closing.

Thank you!

**Pull request closed without merging**
