### PR TITLE
feature: add architecture for security

### PR DESCRIPTION
**Pull request by sbender9**
Replaces #216

Adding a way for developers to add authentication/authorization to node server via a special security plugin.

### CODE REVIEW

**Comment by tkurki** [comment]
This looks good, but needs 
- [ ] documentation (minimum)
- [ ] a sample implementation (preferably)

**Comment by sbender9** [comment]
For the sample implementation is the sk-simple-token-security enough? Or you want something else?

**Comment by tkurki** [comment]
That's enough for now I think.

**Comment by tkurki** [comment]
Fixed some typos, added a few words to the doc, squashed and merged in f16111ccd05901651ce6986743c59a9f49a1381b and 3802519d5039b3305f0061380f97c876534c8f1b. 

Yay!!!!

**Pull request closed without merging**
