### PR TITLE
Chartedsails data log links

### PR DESCRIPTION
**Pull request by tkurki**
Add links to open log files in chartedsails.com if it is available (we are online).

Depends on #652 

image

### CODE REVIEW

**Comment by sarfata** [comment]
@tkurki I am changing the URL format to: `https://beta.chartedsails.com/trip/openurl?url=xxx` (you can try on the beta site) - it will go live soon. 

Can you take that change in before you merge?

**Comment by tkurki** [comment]
@sarfata links like https://beta.chartedsails.com/?url=http://localhost:3000/logfiles/skserver-raw_2018-11-06T21.log do not work. http://chartedsails.com/?url=http://localhost:3000/logfiles/skserver-raw_2018-11-06T21.log works.

**Comment by tkurki** [comment]
Extra commit removed by rebasing on master.

**Comment by sarfata** [comment]
I think we misunderstood each other. It's not just the domain name that changed but also the path. You need to use `/trip/openurl?url=` now. It's live now so you can test.

**Comment by sarfata** [comment]
Example: https://www.chartedsails.com/trip/openurl?url=https://s3-eu-west-1.amazonaws.com/chartedsails-storage/Peter%20Burling.vcc

**Pull request merged**
