### PR TITLE
Added error handling code to pipedproviders.js

### PR DESCRIPTION
**Pull request by fabdrol**
This PR includes error handling for piped providers, plus some other things: 
- When a provider emits an error (unpiping itself and breaking the pipeline - effectively stopping the server) all providers are cleaned (listeners removed, unpiped and set to `null`) and the pipeline is restarted. 
- Cleaned up `pipedproviders.js` and updated to ES2015
- Change to `.travis.yml` to make Travis use a more recent version of Node.js

### CODE REVIEW

**Comment by fabdrol** [comment]
@tkurki objections to merging? This makes providers more robust

**Comment by tkurki** [comment]
How about upgrading the node version in other SK modules as well?

**Comment by tkurki** [comment]
How is error-test used? It doesn't really behave like an unhandled error in provider would, as it calls done.

I would prefer having test code separate.

**Comment by tkurki** [comment]
Is there something changed in the settings files?

**Comment by tkurki** [comment]
Travis and package.json node versions are now not in line.

**Comment by fabdrol** [comment]
Error-test isn't really a useful file, I used that with varying content to test various cases. Should have been deleted.

**Comment by fabdrol** [comment]
I just pushed a new commit where I removed the "engines" key from package.json - as it's not part of the standard and isn't used anywhere except on Heroku.

**Comment by fabdrol** [comment]
@tkurki any objections to merging? Others (Joachim Bakke) are having issues with the server that are solved by this code.

**Comment by tkurki** [comment]
If a single provider throws an error why do we restart everything? 

This will cause all providers to lose state, a practical example being multiline AIS messages.

**Comment by tkurki** [comment]
There have been few if any problem reports related to this. 

A test or several would definitely be in order, but to your question ’is it possible’ there is one easy way to find out: try writing a test.

**Comment by webmasterkai** [comment]
Two years without activity. Can this be closed without merge?

**Pull request closed without merging**
